# Generated by Django 4.0.6 on 2022-09-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosspay_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_user',
            field=models.ImageField(blank=True, upload_to='Images_Banner'),
        ),
    ]
