# Generated by Django 4.0.6 on 2022-09-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosspay_auth', '0003_user_facebook_user_instagram_user_tweeter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook',
            field=models.URLField(default='https', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram',
            field=models.URLField(default='https', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='tweeter',
            field=models.URLField(default='https', max_length=500),
        ),
    ]
