# Generated by Django 4.0.6 on 2022-09-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crosspay_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creat_ad',
            name='other_information',
        ),
        migrations.RemoveField(
            model_name='creat_ad',
            name='outside',
        ),
    ]
