# Generated by Django 4.0.6 on 2022-09-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crosspay_user', '0002_remove_creat_ad_other_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creat_ad',
            name='price_per_m',
        ),
    ]
