# Generated by Django 4.0.6 on 2022-09-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosspay_user', '0003_remove_creat_ad_price_per_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creat_ad',
            name='main_description',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='creat_ad',
            name='main_img',
            field=models.ImageField(upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='creat_ad',
            name='main_price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='creat_ad',
            name='main_titre',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='creat_ad',
            name='property_type',
            field=models.CharField(max_length=100),
        ),
    ]
