# Generated by Django 4.0.6 on 2022-09-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosspay_user', '0004_alter_creat_ad_main_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creat_ad',
            name='year_built',
            field=models.CharField(max_length=10),
        ),
    ]
