# Generated by Django 4.0.6 on 2022-09-21 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crosspay_user', '0005_alter_creat_ad_year_built'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creat_ad',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='creat_ad',
            name='distance_neightbors',
        ),
        migrations.RemoveField(
            model_name='creat_ad',
            name='main_description',
        ),
        migrations.RemoveField(
            model_name='creat_ad',
            name='main_img',
        ),
        migrations.RemoveField(
            model_name='creat_ad',
            name='main_price',
        ),
        migrations.RemoveField(
            model_name='creat_ad',
            name='main_titre',
        ),
        migrations.RemoveField(
            model_name='creat_ad',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='creat_ad',
            name='total_piece',
        ),
        migrations.AlterField(
            model_name='creat_ad',
            name='address',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='creat_ad',
            name='more_info',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='creat_ad',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create', to=settings.AUTH_USER_MODEL),
        ),
    ]
