# Generated by Django 4.0.6 on 2022-09-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosspay_user', '0007_alter_creat_ad_gallery_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creat_ad',
            name='gallery_image1',
            field=models.ImageField(blank=True, upload_to='ad'),
        ),
        migrations.AlterField(
            model_name='creat_ad',
            name='gallery_image10',
            field=models.ImageField(blank=True, upload_to='ad'),
        ),
        migrations.AlterField(
            model_name='creat_ad',
            name='gallery_image11',
            field=models.ImageField(blank=True, upload_to='ad'),
        ),
        migrations.AlterField(
            model_name='creat_ad',
            name='gallery_image12',
            field=models.ImageField(blank=True, upload_to='ad'),
        ),
        migrations.AlterField(
            model_name='creat_ad',
            name='gallery_image2',
            field=models.ImageField(blank=True, upload_to='ad'),
        ),
        migrations.AlterField(
            model_name='creat_ad',
            name='gallery_image3',
            field=models.ImageField(blank=True, upload_to='ad'),
        ),
        migrations.AlterField(
            model_name='creat_ad',
            name='gallery_image4',
            field=models.ImageField(blank=True, upload_to='ad'),
        ),
        migrations.AlterField(
            model_name='creat_ad',
            name='gallery_image5',
            field=models.ImageField(blank=True, upload_to='ad'),
        ),
        migrations.AlterField(
            model_name='creat_ad',
            name='gallery_image6',
            field=models.ImageField(blank=True, upload_to='ad'),
        ),
        migrations.AlterField(
            model_name='creat_ad',
            name='gallery_image7',
            field=models.ImageField(blank=True, upload_to='ad'),
        ),
        migrations.AlterField(
            model_name='creat_ad',
            name='gallery_image8',
            field=models.ImageField(blank=True, upload_to='ad'),
        ),
        migrations.AlterField(
            model_name='creat_ad',
            name='gallery_image9',
            field=models.ImageField(blank=True, upload_to='ad'),
        ),
    ]
