# Generated by Django 4.0.6 on 2022-09-21 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crosspay_user', '0008_alter_creat_ad_gallery_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creat_ad',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create', to=settings.AUTH_USER_MODEL),
        ),
    ]
