# Generated by Django 4.0.6 on 2022-09-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosspay_user', '0009_alter_creat_ad_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creat_ad',
            name='gallery_image1',
            field=models.FileField(blank=True, upload_to='ad'),
        ),
    ]
