# Generated by Django 4.0.6 on 2022-09-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crosspay_user', '0013_alter_creat_ad_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creat_ad',
            old_name='Titre',
            new_name='titre',
        ),
    ]
